### ISSUE TITLE
(minor) bugs to fix

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/hBayesDM#111]
- Add cgt_cm and any new models to hBayesDM.R
    - Check `?hBayesDM`    # currently cgt_cm is missing in the list

- add cgt_cm to the plotting function
    - `output = cgt_cm("example", 2000, 1000, 3, 3); plot(output)`  # it generates an error

**Comment by JaeyeongYang** [comment]
Fixed with the version 1.0.1.
