### ISSUE TITLE
bandit4arm2_kalman_filter does not work with its example data

### ISSUE THREAD

**Issue by Heeseung-Lee** [CCS-Lab/hBayesDM#128]
When I run the code below, I found that bandit4arm2_kalman_filter does not work.

```
library(hBayesDM)
output = bandit4arm2_kalman_filter(data="example", niter=2000, nwarmup=1000, nchain=4, ncore=4)
```
The error message is too long but I excerpted a seemingly critical sentence here.
```
Chain 1: Unrecoverable error evaluating the log probability at the initial value.
Chain 1: mismatch in dimension declared and found in context; processing stage=parameter initialization; variable name=sigma; position=0; dims declared=(6); dims found=(46)
[1] "Error in sampler$call_sampler(args_list[[i]]) : "                                                                                                                     
[2] "  mismatch in dimension declared and found in context; processing stage=parameter initialization; variable name=sigma; position=0; dims declared=(6); dims found=(46)"
error occurred during calling the sampler; sampling not done
```

Do you have any suggestions?

**Comment by youngahn** [comment]
Hi Heeseung,

I think initialization with VB-based initial values doesn't seem to work and sorry for the inconvenience. Could you try this (trying different initial values)?

output = bandit4arm2_kalman_filter(data="example", inits = "fixed", niter=2000, nwarmup=1000, ... )

Best,
Young

**Comment by Heeseung-Lee** [comment]
Thanks, Young!
The code ran successfully after modifying the "inits" parameter as your advice.
