### ISSUE TITLE
Bug in bart_ewmv Python model

### ISSUE THREAD

**Issue by CarlyLasagna** [CCS-Lab/hBayesDM#130]
I found a bug in the bart_ewmv Python model that is preventing starting values obtained from ADVI samples from being fed into the main model. As a result, when using the default parameters (when inits='vb') the model is forced to start from random values even when vb estimates are obtained successfully via the ADVI algorithm.

This appears to come from a discrepancy in how variables are defined in the bart_ewmv.stan file ("mu_p"; line 29) and how they are called in the base.py file ("mu_pr"; line 462). I resolved this issue by simply changing all instances of the variable name in the bart ewmv stan file from "mu_p" to "mu_pr".

**Comment by JaeyeongYang** [comment]
Hi @CarlyLasagna, thanks for your feedback.

As I understand, I fixed this issue in the latest hBayesDM 1.1.1. Could you check out if it's working with the latest version?

Best,
Jaeyeong

**Comment by JaeyeongYang** [comment]
As I solved this issue in the latest version, I close this issue. If the issue still exists, please let me know.

**Comment by CarlyLasagna** [comment]
That fixed it. Thanks!
