### ISSUE TITLE
bart_ewmv model NaN error

### ISSUE THREAD

**Issue by apike02** [CCS-Lab/hBayesDM#135]
Hi there, 

I've been having issues with the bart_ewmv model, such that when I try to run it on a dataset that I know works with the bart_par4 model it doesn't run. See error message below:
![image](https://user-images.githubusercontent.com/26331350/124588866-36521b80-de51-11eb-962c-67992121df74.png)

I think I've isolated the issue to the fact that some participants did not pump the balloon up at all on initial trials, so the row in the data is, for example:

11 0 0

It seems that having a 0-pump is ok when this isn't the first trial, so I suspect it's an issue with how the initial values are learnt or calculated. The model runs fine with the example data, and with data that I've deliberately edited such that the above issue (a zero-pump on trial 1) doesn't occur. 

Thanks for all your hard work on these models! 

Alex

**Comment by JaeyeongYang** [comment]
Hi Alex,

Thanks for clarifying the issue! Please let us check out the model and try to fix it.

Great thanks!

Jaeyeong

**Comment by apike02** [comment]
I think I've identified what the issue may be - this line 
`p_burst = phi[j] + (1 - exp(-n_pump * eta[j])) * ((0.0 + n_pump - n_succ) / n_pump - phi[j])`
 requires n_pump to be >0 for the fraction to be defined. I think maybe one hacky solution I might use now is that p_burst clearly can't be updated if the participant hasn't pumped the balloon up, so maybe p_burst should only be updated if n_pump>0?

**Comment by JaeyeongYang** [comment]
Solved with #136.
