### ISSUE TITLE
Creating new models in hBayesDM

### ISSUE THREAD

**Issue by apike02** [CCS-Lab/hBayesDM#139]
Hi there,

I've been creating some modified versions of the Stan models, and ran into an issue where I followed all the instructions here: https://github.com/CCS-Lab/hBayesDM/wiki/How-to-add-new-model but trying to run a model resulted in the following error:

```
fit<-bart_ewmv(data=file,vb=TRUE,ncore=1)

Model name  = bart_ewmv 
Data file   = C:/.../data//bart_lc_modeldata_pilot.txt 

Details:
 Using variational inference
 # of subjects                  = 69 
 # of (max) trials per subject  = 30 

```
> Warning in normalizePath(path.expand(path), winslash, mustWork) :
>   path[1]="": The filename, directory name, or volume label syntax is incorrect
> Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
>   Empty or invalid filename!

On inspection, after running devtools::install(), there was no stan_files directory in the hBayesDM folder in my R win-library, but just an empty file with that title ('stan_files'). I copied the stan_files over from the development directory in the end, but I'm not sure if this is something that could be fixed? Running the process on linux worked fine, so I think it's a windows-specific issue. 
I'm running RStudio Version 1.4.1717 with the following R version: 
x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen

**Comment by youngahn** [comment]
@lehlsy0904 and @JeunghyunLee will check this and try to replicate the error messages.

**Comment by lehlsy0904** [comment]
Many apologies for the delay. We have conducted tests on our local machines, and confirmed that we could add the new model without any issues. The problem you are currently facing could be related to an incorrect path. Therefore, we request you to check if your machine is correctly locating the library by using the `.libPath()` function.

Please let us know if you have any additional concerns.

**Comment by apike02** [comment]
Hi - sorry, it was a while ago that I did this, and I'm not currently able to check it as I now use a Mac. Did you test on Windows machines? I hadn't set the path at all so this shouldn't have been an issue - I followed the instructions as written, and stan_files was created but not a directory, just an empty file.

**Comment by lehlsy0904** [comment]
Hi! When working with Windows machines, you may encounter an issue where your machine automatically sets the incorrect path, especially if you've reinstalled different versions of R multiple times. This can result in an empty folder under the correct path. If you encounter this problem, follow these steps to resolve it:

Verify hBayesDM Library: First, ensure that the hBayesDM library is built on the correct path and is not empty.

Check Library Path: If the library is empty, you will need to remove the hBayesDM package from your current R version.

Locate Correct Library Path: Manually find the library path that corresponds to your current R version.

Reinstall hBayesDM Package: After locating the correct library path, reinstall the hBayesDM package on your system.

By following these steps, you should be able to resolve any issues related to incorrect paths and ensure the hBayesDM package is properly installed in the right location. If you encounter any difficulties or need further assistance, feel free to ask for help!

**Comment by apike02** [comment]
Thank you! I will try this if I encounter this problem again.
