### ISSUE TITLE
Choice preservation

### ISSUE THREAD

**Issue by SebastianSpeer** [CCS-Lab/hBayesDM#145]
Dear HBayesDM team,

In the Reference section I see several models without choice preservation, but is there also an implementation with choice preservation?

If not do you have an example of how to implement this?

Thanks a lot for your help,

Sebastian

**Comment by JaeyeongYang** [comment]
Hi Sebastian,

I'm not sure what you meant by "choice preservation" parameter, but still, the documentation includes all the models hBayesDM provides, so there is no implementation for models with choice preservation yet.

If you want to implement a model with hBayesDM, I recommend you to take a look at this page ([link](https://github.com/CCS-Lab/hBayesDM/wiki/How-to-contribute)) for details.

Thanks for your interests on hBayesDM.

Best regards,
Jaeyeong
