### ISSUE TITLE
code of pst_gainloss_Q 

### ISSUE THREAD

**Issue by Dengyuti** [CCS-Lab/hBayesDM#147]
Hi, I tried to use the code in the instructions, but it gave an error.
Here is the code:
df <- read.table("D:/YT/ten.txt",header = TRUE)
fit <- pst_gainloss_Q(df, niter = 4000, nchain = 4, ncore = 1)

Here are the bugs:
Error in nchar(errmsg) : invalid multibyte string, element 7
In addition: Warning messages:
1: In is.null(data) || is.na(data) :
  'length(x) = 240 > 1' in coercion to 'logical(1)'
2: In is.null(data) || is.na(data) || data == "" :
  'length(x) = 240 > 1' in coercion to 'logical(1)'
Error in sink(type = "output") : invalid connection

Thank you for your help！

**Comment by youngahn** [comment]
Many apologies for the delay. For questions like this, please use our mailing list: https://groups.google.com/g/hbayesdm-users. Also, make sure to include your (sample) dataset so that our team can replicate the error messages.
