### ISSUE TITLE
Issue fitting candidate models in HbayesDM 1.2.0 and 1.1.0

### ISSUE THREAD

**Issue by ashleyyeh182** [CCS-Lab/hBayesDM#150]
I'm new to HbayesDM and have been trying to fit candidate models for my data, but I've been having a lot of trouble. 

Originally I had been using HbayesDM 1.1.0 and I tried running the drift-diffusion model with the following code: 

choiceRT_ddm(
  data = "choose",
  niter = 4000,
  nwarmup = 1000,
  nchain = 4,
  ncore = 4,
  nthin = 1,
  inits = "vb",
  indPars = "mean",
  modelRegressor = FALSE,
  vb = FALSE,
  inc_postpred = FALSE,
  adapt_delta = 0.95,
  stepsize = 1,
  max_treedepth = 10
)

I also tried using:

output1 = choiceRT_ddm(data="choose", niter=2000, nwarmup=1000, nchain=4, ncore=4)

The model fitting took longer than 10 minutes and several error messages came up, but in the end, it said "model fitting is complete". However, I tried to call the functions "output1$allIndPars" or "output1$fit" and the data that came up was completely blank, and "output 1" was empty. Thinking there was probably something wrong with my dataset (even though I had the correct columns and no NA values, etc.), I tried substituting the data for "example" to use the example data. However, this led to the exact same result. Then, I updated my R, the drift-diffusion package (1.2.0), and the RStan to the latest versions and ran the same code with the example data: 

choiceRT_ddm(
  data = "example",
  niter = 4000,
  nwarmup = 1000,
  nchain = 4,
  ncore = 4,
  nthin = 1,
  inits = "vb",
  indPars = "mean",
  modelRegressor = FALSE,
  vb = FALSE,
  inc_postpred = FALSE,
  adapt_delta = 0.95,
  stepsize = 1,
  max_treedepth = 10
)

This time, the model fitting just took a very long time, I ran the code and came back a few hours later and it was still running. However, when I tried to run other models, such as 

output1 = gng_m1(data="example", niter=2000, nwarmup=1000, nchain=4, ncore=4)

Everything ran perfectly and exactly how the guide said it would. Please let me know if there is anything I should do to run the drift diffusion model, I would really like this model to work and would appreciate any guidance!

**Comment by youngahn** [comment]
Many apologies for the delay. For questions like this, please use our mailing list: https://groups.google.com/g/hbayesdm-users. Also, make sure to include your (sample) dataset so that our team can replicate the error messages.
