### ISSUE TITLE
Error in HbayesDM model (banditNarm_delta)

### ISSUE THREAD

**Issue by kshtjkumar** [CCS-Lab/hBayesDM#154]
when I use this output <- banditNarm_kalman_filter(data = df, niter = 2000, nwarmup = 1000, nchain = 4, ncore = 4), rest all columns and everything is as per the documentation.  I get the following error, even if i run othe n arm bandit models, i get the same error. Can you help ?

****************************************
** Use VB estimates as initial values **
****************************************
Chain 1: ------------------------------------------------------------
Chain 1: EXPERIMENTAL ALGORITHM:
Chain 1:   This procedure has not been thoroughly tested and may be unstable
Chain 1:   or buggy. The interface is subject to change.
Chain 1: ------------------------------------------------------------
Chain 1: 
Chain 1: 

 *** caught segfault ***
address 0x80, cause 'invalid permissions'

Traceback:
 1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x6000022c6400>,     dll = list(name = "Rcpp", path = "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x8068dbd0>,         info = <pointer: 0x6000007caca0>), numParameters = -1L),     <pointer: 0x600001fe6e00>, <pointer: 0x600002588800>, .pointer,     ...)
 2: sampler$call_sampler(c(args, dotlist))
 3: .local(object, ...)
 4: rstan::vb(object = stanmodel_arg, data = data_list)
 5: rstan::vb(object = stanmodel_arg, data = data_list)
 6: make_gen_init_from_vb()
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(make_gen_init_from_vb(), error = function(e) {    cat("\n")    cat("******************************************\n")    cat("** Failed to obtain VB estimates.       **\n")    cat("** Use random values as initial values. **\n")    cat("******************************************\n")    return("random")})
11: banditNarm_delta(data = data, niter = 2000, nwarmup = 1000, nchain = 4,     ncore = 4)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by youngahn** [comment]
Many apologies for the delay. For questions like this, please use our mailing list: https://groups.google.com/g/hbayesdm-users. Also, make sure to include your (sample) dataset so that our team can replicate the error messages.
