### ISSUE TITLE
Parameterization of K in delay-discount models

### ISSUE THREAD

**Issue by jerlich** [CCS-Lab/hBayesDM#17]
Thanks for these useful models.  When we fit K across subjects (using various methods), we find that the distribution of K is better described by  log-normal than a normal distribution.

From my reading of stan documentation, models do better if they are parameterized as unimodal gaussian. 

Have you considered fitting log(k) instead of k?

**Comment by jerlich** [comment]
Nevermind! Sorry, i see that you do that already.

**Comment by youngahn** [comment]
Thanks for asking. I believe 'k' is estimated (parameterized as unimodal Gaussian) and then it is transformed into natural log(k) for users. Hope it's fine with you!
