### ISSUE TITLE
Removing NAs cases not in necessary columns

### ISSUE THREAD

**Issue by Nathaniel-Haines** [CCS-Lab/hBayesDM#19]
I realized that when we remove cases (i.e. rows) which contain NA values before processing the raw data, we include unnecessary columns. We should change this so that only cases with NA in the columns necessary for modeling are removed.

**Comment by youngahn** [comment]
Thanks for reporting this. Let's change this in the next version.

**Comment by JaeyeongYang** [comment]
Solved with #45.
