### ISSUE TITLE
Reorganize files into common themes

### ISSUE THREAD

**Issue by paulhendricks** [CCS-Lab/hBayesDM#3]
As opposed to each function having its one file, common themes should be identified and the functions should be placed into each file per the theme....

e.g. plotting functions should go into a `plot.R` rile, modeling functions should go into a `model.R` file, etc.

**Comment by youngahn** [comment]
What do you mean by the 'theme'? 
I'm not sure if it would be a good idea to put all model files into a single `model.R` file. I'm afraid users will have hard time to find and understand each model. Any suggestions?

**Comment by paulhendricks** [comment]
That is a good point. There's a delicate balance between having all functions in one file and having one function per file. 

I'll look through each file more carefully and provide some suggestions.

**Comment by youngahn** [comment]
Reorganized the folders based on the guidelines for Stan-based R packages (https://cran.r-project.org/web/packages/rstantools/vignettes/developer-guidelines.html). Closing this issue for now.
