### ISSUE TITLE
trying deprecated constructor; please alert package maintainer

### ISSUE THREAD

**Issue by fusaroli** [CCS-Lab/hBayesDM#32]
I have been trying the tutorial of the package, and when using this line:

> output1 = gng_m1(data="example", niter=2000, nwarmup=1000, nchain=4, ncore=4)

I get 
> trying deprecated constructor; please alert package maintainer
, as well as a series of
> [1] "Error in sampler$call_sampler(args_list[[i]]) : "
> [2] "  c++ exception (unknown reason)"                
> error occurred during calling the sampler; sampling not done
> trying deprecated constructor; please alert package maintainer

The model runs in the end.

**Comment by youngahn** [comment]
Thanks for reporting it. I believe the `trying deprecated constructor...` message is an issue Stan developers try to fix in the near future. As you said, the model runs despite the warning. 

``plot(output1, type="trace", fontSize=11)``
--> Did you run it in RStudio? I wonder if it is related to the size of a plotting window in RStudio. It runs without a problem in my computers... Could you try this? Could you open a new graph window (`x11()` or `quartz()`) before creating a new graph?

**Comment by fusaroli** [comment]
as per the plot: yes, I ran it in RStudio. I opened a new graph window as well, but no luck. I also tried running it directly in the R console, but I get the same issue.

**Comment by youngahn** [comment]
Are you using a Windows, Mac, or Linux?

**Comment by fusaroli** [comment]
github version of the package (0.5.0), rstan 2.17.3, r 3.4.3, on a High Sierra Mac Os.

**Comment by youngahn** [comment]
Strange... I'm using identical GitHub, RStan, R, Mac OS X versions. We made some changed over the last a few days and could you reinstall the GitHub version? 

```
# install 'devtools' if required
if (!require(devtools)) install.packages("devtools")  
devtools::install_github("CCS-Lab/hBayesDM")
```

**Comment by fusaroli** [comment]
I reinstalled the package (from github). Same error as before for the plot. Plus I had to run the model 3 times before I actually got it to sample.

**Comment by youngahn** [comment]
Hmm... it's hard for me to reproduce the problem. I also don't know why you had to run the model 3 times with the sample data. It would be most helpful if you could upload the output messages as they are to address the issue. Anyway thanks for reporting again.

**Comment by fusaroli** [comment]
Sorry for the lack of clarity. Also, I'm mostly interested in the stancode to be adapted for one of my projects, so a fix is not necessary for me, I just thought to let you know of the issue.

And thanks for the package, the stancode is really speeding up my work!

In any case, this is what I'm getting when running the tutorial:

> Model name =  gng_m1 
> Data file  =  /Library/Frameworks/R.framework/Versions/3.4/Resources/library/hBayesDM/extdata/gng_exampleData.txt 
> 
> Details:
>  # of chains                   =  4 
>  # of cores used               =  4 
>  # of MCMC samples (per chain) =  2000 
>  # of burn-in samples          =  1000 
>  # of subjects                 =  10 
>  # of (max) trials per subject =  240 

> ***********************************
> **  Loading a precompiled model  **
> ***********************************
> trying deprecated constructor; please alert package maintainer
> starting worker pid=25969 on localhost:11500 at 16:21:48.293
> starting worker pid=25977 on localhost:11500 at 16:21:48.485
> starting worker pid=25985 on localhost:11500 at 16:21:48.675
> starting worker pid=25993 on localhost:11500 at 16:21:48.848
> trying deprecated constructor; please alert package maintainer
> 
> SAMPLING FOR MODEL 'gng_m1' NOW (CHAIN 1).
> 
> Gradient evaluation took 0.001487 seconds
> 1000 transitions using 10 leapfrog steps per transition would take 14.87 seconds.
> Adjust your expectations accordingly!
> 
> 
> [1] "Error in sampler$call_sampler(args_list[[i]]) : "
> [2] "  c++ exception (unknown reason)"                
> error occurred during calling the sampler; sampling not done
> trying deprecated constructor; please alert package maintainer

Repeat for all the other chains. No samples are produced.

**Comment by youngahn** [comment]
If you haven't, could you check if Stan is correctly installed by trying the "eight schools" example in this link: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started? 

And check this link as well: https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux.

**Comment by youngahn** [comment]
@fusaroli Is the problem solved? If so, I will close this issue.
