### ISSUE TITLE
choiceRT_ddm error

### ISSUE THREAD

**Issue by Nathaniel-Haines** [CCS-Lab/hBayesDM#44]
In the choiceRT_ddm model on line 46 of the stan code: 

tau[i]  = Phi_approx(mu_p[4] + sigma[4] * tau_pr[i]) * (**minRT[N]**-RTbound) + RTbound;

The bolded term should instead be: 

tau[i]  = Phi_approx(mu_p[4] + sigma[4] * tau_pr[i]) * (**minRT[i]**-RTbound) + RTbound;  

Otherwise, tau is not being constrained by the lowest RT for each subject. This will not affect other model parameters or how well the model fits, but it should be modified to constrain tau appropriately.

**Comment by JaeyeongYang** [comment]
I'll fix it in the version `0.6.2`. Thanks for reporting. 😀

**Comment by JaeyeongYang** [comment]
Solved with `hotfix/v0.6.2`.
