### ISSUE TITLE
Solving build failure of Travis CI

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#51]
From some point in the history of the package, travis CI began failing the builds.
It would be best if we could figure out the root of the problem and get it to work!

**Comment by dlemfh96** [comment]
Note process of the branch 'experiment/attempt-to-fix-travis-CI-build'

**Comment by dlemfh96** [comment]
Some suspicions are:
- An error that roots from sth related to rstan

See this error message caused by Travis build:
<img width="686" alt="default" src="https://user-images.githubusercontent.com/37664182/47255933-c938a500-d4b2-11e8-9941-7a3055aacda1.PNG">

Travis seems to try to use StanHeaders and rstan of versions 2.18.x

See here for entire error message:
https://travis-ci.org/CCS-Lab/hBayesDM/jobs/444064074

**Comment by JaeyeongYang** [comment]
As an extension of the discussion on commit https://github.com/CCS-Lab/hBayesDM/commit/24828932d754aae2bf0dba863c824ce2e16f7628, the first thing we should try is making the Travis CI setting compatible for CXX14 rather than not using rstan 2.18.x.

Here is one reference which tried to use C++14 for R in Travis CI: http://dirk.eddelbuettel.com/blog/2017/06/13/

**Comment by JaeyeongYang** [comment]
Currently, two jobs for linux (g++-7, clang++-7) are stuck with the option `-lgfortran`.

**Comment by dlemfh96** [comment]
Currently, both 'stan-dev/rstan' and 'stan-dev/rstanarm' repos are failing their recent Travis CI builds.

It seems that while Travis uses its own virtual environment to check builds, the stan-devs haven't yet figured out a way to make the rstan package pass the build (in the specific environment Travis is using).

Thus, it may be best to postpone this issue until the rstan dev team figures out a way to pass the Travis builds for their repos.

**Comment by JaeyeongYang** [comment]
Then, for now, I'll make it conduct CI on mac only.

**Comment by JaeyeongYang** [comment]
Solved with #55. I temporarily disabled jobs for mac, not for linux. Later we should re-enable them.
