### ISSUE TITLE
Update obsolete package structure

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#57]
Current hBayesDM package structure follows the skeleton provided by `rstantools` of Jan 2017.
Since then, the Stan dev team has updated the package structure offered by `rstantools`.

A quick list of changes include:
- `exec/` -> `src/stan_files/`
- `inst/chunks/` -> `src/stan_files/chunks/`
- `make_cpp.R` -> `make_cc.R`
- `models.hpp` -> individual files in `src/stan_files/`
- `Modules.cpp` -> individual files in `src/stan_files/`
- `Makevars{.win}`
- `cleanup{.win}` -> *removed*
- `R/stanmodels.R`
- `R/zzz.R`
- `hBayesDM.R` -> `hBayesDM-package.R`
- `inst/extdata/` -> `data/`
- *Does not keep track of `*.cpp`/`*.cc`/`*.hpp`/`*.o` files in repo source, but instead builds them from scratch every time `R CMD build` is executed.*

Updating the package structure will solve the warning message regarding:
`Using deprecated constructor; please alert package manager`
(To pinpoint the exact cause of this message, it comes from the `constructor` argument in function call to `exposeClass()` in `stanmodels.R`.)

#### Reference
https://discourse.mc-stan.org/t/developing-a-package-that-uses-rstan-pre-translated-c-files/6251

## Update Progress (Dec 8th ~)
Branch: `release/v0.7.0-update-package-structure`

File (path from root) | Type of change | Done
-|-|-
`R/zzz.R` | edit | o
`R/stanmodels.R` | edit | o
`exec/` → `src/stan_files/` | relocate | o
`inst/chunks/license.stan` → `src/stan_files/pre/license.stan` | relocate; edit | o
`.gitignore` | edit | o
`tools/make_cpp.R` → `tools/make_cc.R` | rename; edit | o
`inst/include/meta_header.hpp` | create | o
`src/Makevars` | edit | o
`src/Makevars.win` | edit | o
`cleanup` | delete | o
`cleanup.win` | delete | o

**Comment by JaeyeongYang** [comment]
Done through the branch `release/v0.7.0`.
