### ISSUE TITLE
Use '+=' notation in Stan files

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#59]
Currently **a lot** of the Stan files make use of the following type of notation:
![image](https://user-images.githubusercontent.com/37664182/47740388-0d018a80-dcbb-11e8-8240-9ec80a34004e.png)
where a *left-hand-side* variable (`log_lik`) occurs on the *right-hand-side*.

In rstan 2.18.x, this causes the translated c++ file to **deep copy** the object (which is obviously inefficient).
**This is where the Parser warning messages (that began to occur since rstan 2.18.x) are coming from.**

The devs at 'rstanarm' seem to have changed their code to use the '+=' notation in all of their Stan files, as you can see in the following picture:
<img width="753" alt="ref" src="https://user-images.githubusercontent.com/37664182/47740718-d24c2200-dcbb-11e8-9a02-2dabf09e7a94.PNG">

#### It seems like it may be necessary to change all *our* Stan files so that they use the '+=' notation also.

**Comment by JaeyeongYang** [comment]
## Current working status

|  \# | model_function            | done | notes |
|:---:|:--------------------------|:----:|:------|
|  1  | bandit2arm_delta          |
|  2  | bandit4arm_4par           |
|  3  | bandit4arm_lapse          |
|  4  | bandit4arm2_kalman_filter |
|  5  | bart_par4                 |
|  6  | choiceRT_ddm              |
|  7  | choiceRT_ddm_single       |
|  8  | choiceRT_lba              |
|  9  | choiceRT_lba_single       |
| 10  | cra_exp                   |
| 11  | cra_linear                |
| 12  | dbdm_prob_weight          |
| 13  | dd_cs                     |
| 14  | dd_cs_single              |
| 15  | dd_exp                    |
| 16  | dd_hyperbolic             |
| 17  | dd_hyperbolic_single      |
| 18  | gng_m1                    |
| 19  | gng_m2                    |
| 20  | gng_m3                    |
| 21  | gng_m4                    |
| 22  | igt_orl                   |
| 23  | igt_pvl_decay             |
| 24  | igt_pvl_delta             |
| 25  | igt_vpp                   |
| 26  | peer_ocu                  |
| 27  | prl_ewa                   |
| 28  | prl_fictitious            |
| 29  | prl_fictitious_multipleB  |
| 30  | prl_fictitious_rp         |
| 31  | prl_fictitious_rp_woa     |
| 32  | prl_fictitious_woa        |
| 33  | prl_rp                    |
| 34  | prl_rp_multipleB          |
| 35  | pst_gainloss_Q            |
| 36  | ra_noLA                   |
| 37  | ra_noRA                   |
| 38  | ra_prospect               |
| 39  | rdt_happiness             |
| 40  | ts_par4                   |
| 41  | ts_par6                   |
| 42  | ts_par7                   |
| 43  | ug_bayes                  |
| 44  | ug_delta                  |
| 45  | wcs_sql                   |

**Comment by dlemfh96** [comment]
Closed with branch `release/v0.7.0`.
