### ISSUE TITLE
Progress Report Page for Refactorization

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#63]
- All model functions now have the following default values for the following arguments:
  - `niter` = 4000
  - `nwarmup` = 1000
  - `nchain` = 4
  - `ncore` = 1
  - `inits` = "random"

\# | model_function | json | R | doc | test | Notes
-|-|-|-|-|-|-
1 | ra_prospect | o | o | o | o |
2 | igt_pvl_decay | o | o | o | o |
3 | bandit4arm2_kalman_filter | o | o | o | | *issue resolved*
4 | dbdm_prob_weight | o | o | o |
5 | bandit2arm_delta | o | o | o | o |
6 | bandit4arm_4par | o | o | o | o | *issue resolved*
7 | bandit4arm_lapse | o | o | o | o | *issue resolved*
8 | bart_par4 | o | o | o | o | *issue resolved*
9 | choiceRT_ddm | o | o | o | o | *issue resolved*
10 | choiceRT_ddm_single | o | o | o | o |
~11~ | ~choiceRT_lba~ |
~12~ | ~choiceRT_lba_single~ | o |
13 | cra_exp | o | o | o | o | *issue resolved*
14 | cra_linear | o | o | o | o | *issue resolved*
15 | dd_cs | o | o | o | o |
16 | dd_cs_single | o | o | o | o |
17 | dd_exp | o | o | o | o |
18 | dd_hyperbolic | o | o | o | o |
19 | dd_hyperbolic_single | o | o | o | o |
20 | gng_m1 | o | o | o | o |
21 | gng_m2 | o | o | o | o |
22 | gng_m3 | o | o | o | o | *issue resolved*
23 | gng_m4 | o | o | o | o |
24 | igt_orl | o | o | o | o | *issue resolved*
25 | igt_pvl_delta | o | o | o | o |
26 | igt_vpp | o | o | o | o |
27 | peer_ocu | o | o | o | o |
28 | prl_ewa | o | o | o | o | *issue resolved*
29 | prl_fictitious | o | o | o | o |
30 | prl_fictitious_multipleB | o | o | o | o |
31 | prl_fictitious_rp | o | o | o | o |
32 | prl_fictitious_rp_woa | o | o | o | o |
33 | prl_fictitious_woa | o | o | o | o |
34 | prl_rp | o | o | o | o |
35 | prl_rp_multipleB | o | o | o | o |
36 | pst_gainloss_Q | o | o | o | o |
37 | ra_noLA | o | o | o | o |
38 | ra_noRA | o | o | o | o |
39 | rdt_happiness | o | o | o | o |
40 | ts_par4 | o | o | o | o |
41 | ts_par6 | o | o | o | o |
42 | ts_par7 | o | o | o | o |
43 | ug_bayes | o | o | o | o |
44 | ug_delta | o | o | o | o | *issue resolved*
45 | wcs_sql | o | o | o | o | *issue resolved*

#### Total: 43/45 models refactored.

- `choiceRT_lba` models are not refactored because these 2 models are currently written so that total number of parameters change dynamically. This is too much a significant diversion from the current `hBayesDM_model` base function.

## Regarding the Notes:
See the appropriate comment for the Note.
After handling the issue, **please check-mark the box** to indicate that the issue was resolved.
If the issue is not a problem and can be left as it is, just check-mark the box.

When you check-mark the box, please edit the comment to include a message about how the issue was handled.
*(However, please refrain from editing this main article, so that there are no conflicts created from simultaneous edits, as I will be continuously updating this table as I progress on with the refactorization.)*

**Comment by dlemfh96** [comment]
- [ ] 6. bandit4arm_4par

**Comment by dlemfh96** [comment]
- [ ] 7. bandit4arm_lapse

**Comment by dlemfh96** [comment]
- [ ] 8. bart_par4

**Comment by dlemfh96** [comment]
- [ ] 9. choiceRT_ddm

**Comment by dlemfh96** [comment]
- [x] 13. cra_exp

*Leaving as-is, per request of JaeyeongYang.*

**Comment by dlemfh96** [comment]
- [ ] 3. bandit4arm2_kalman_filter

**Comment by dlemfh96** [comment]
- [ ] 22. gng_m3

👉 In (.R) file of `gng_m3`, the initial values for parameters `b` & `pi` are given as (both) `0.1`.
However, the initial values for the same parameters are given as (both) `0` in `gng_m2` & `gng_m4`.
Since there is a discrepancy, I am reporting it here.

**Comment by dlemfh96** [comment]
- [ ] 24. igt_orl

👉 For parameter `K`:
(.R) file bounds are [0, 10], while (.stan) file constraints are [0, 5].

**Comment by dlemfh96** [comment]
- [ ] 28. prl_ewa

👉 For the same parameter `beta` (inverse temperature):

The following four prl models have the bounds [0, 10]:
> `prl_ewa`, `prl_fictitious_multipleB`, `prl_rp`, `prl_rp_multipleB`

However, the following four prl models have the bounds [0, 5]:
> `prl_fictitious`, `prl_fictitious_rp`, `prl_fictitious_rp_woa`, `prl_fictitious_woa`

**Comment by dlemfh96** [comment]
- [ ] 43. ug_bayes

👉 For the same parameter `tau` (inverse temperature):
`ug_bayes.R` designates the initial value as `1`, while `ug_delta.R` designates initial value as `0.5`.

**Comment by JaeyeongYang** [comment]
It would be good to do so to include the LBA model and other models that are hard to implement with Matt trick. Let's split it into a separate issue.

**Comment by JaeyeongYang** [comment]
Oh, there already exists a separate issue for `choiceRT_lba` (#65). Let's do this on there.

**Comment by dlemfh96** [comment]
#### All minor issues resolved as of Dec 5.
