### ISSUE TITLE
Uniform priors and matching constraints for parameters in choiceRT_ddm_single.stan

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#64]
In current `choiceRT_ddm_single.stan` ([link](https://github.com/CCS-Lab/hBayesDM/blob/feature/update-models--with-model-func/exec/choiceRT_ddm_single.stan)),
uniform priors (for parameters `alpha`, `beta`, `tau`) are declared like the following:

![image](https://user-images.githubusercontent.com/37664182/48315068-2d173f00-e615-11e8-804e-577c3644e799.png)

However, according to the Stan User's Manual, it's better if the variable constraints match the bounds of the prior uniform distribution.

![image](https://user-images.githubusercontent.com/37664182/48315088-520bb200-e615-11e8-846e-6e16c9bf6391.png)

All other Stan files in `exec/` have been checked to see if uniform distribution priors match the parameters' declared constraints. (And they all do.)

**Comment by JaeyeongYang** [comment]
Then, can writing Stan codes as below solve the issue?

```stan
parameters {
  real<lower=0,upper=5> alpha;
  real<lower=0,upper=1> beta;
  real<lower=0> delta;
  real<lower=RTbound,upper=minRT> tau;
}

model {
  alpha ~ uniform(0, 5);
  beta ~ uniform(0, 1);
  delta ~ normal(0, 2);
  tau ~ uniform(RTbound, minRT);
}
```

**Comment by dlemfh96** [comment]
I'll do that.
