### ISSUE TITLE
Matt trick for choiceRT_lba model

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#65]
The `choiceRT_lba` model is the **only** (non-"single"-type) model that does not make use of Matt trick in R and Stan codes.
Currently, it’s not possible to use `hBayesDM_model` to rewrite `choiceRT_lba.R`, because of this fact.
`choiceRT_lba.stan` should be edited to employ Matt trick.

**Comment by JaeyeongYang** [comment]
Rather, modifying `hBayesDM_model` to cover models without using Matt trick might be the desired way to go. There can be any other (future) models that are hard to implement with Matt trick, and in that cases, we will have some troubles.

**Comment by JaeyeongYang** [comment]
I suggest adding a new argument `use_matt_trick` for `hBayesDM_model`. If this argument is `TRUE`, go as currently implemented; if not, use parameter names as it is, as for `single` models.

**Comment by JaeyeongYang** [comment]
For now, this issue is closed due to the variable number of model parameters of currently implemented LBA models. Maybe implementing new version of LBA models with a fixed number of parameters can be a way to go instead.
