### ISSUE TITLE
Model regressors for cra_exp & cra_linear

### ISSUE THREAD

**Issue by dlemfh96** [CCS-Lab/hBayesDM#67]
`cra_exp` tries to extract model regressors "sv" & "p_var".
However, these variables are not defined in the Stan file.
So running `cra_exp(modelRegressor = TRUE)` gives the following error.

<img width="395" alt="cra_exp_output" src="https://user-images.githubusercontent.com/37664182/48395238-f991fd00-e759-11e8-85d0-084bdb82a651.PNG">

`cra_linear` also does not have modelRegressors support.

👉 Disabling modelRegressor for `cra_exp` (& `cra_linear`) for now.
I created this issue per request of @JaeyeongYang, as a reminder to add regressor feature to `cra_exp` & `cra_linear` in the near future.

**Comment by dlemfh96** [comment]
@JaeyeongYang 
Please make sure that the regressor variable identifiers are the same for (.R) and (.stan) files!

**Comment by JaeyeongYang** [comment]
Solved with PR #71.
