### ISSUE TITLE
Create a simple GUI for creating model JSON files

### ISSUE THREAD

**Issue by dlemfh** [CCS-Lab/hBayesDM#89]
It would be even easier to contribute to hBayesDM if there was a simple GUI (like Google Form or simple Javascript or Django Applet) to take user input and automatically create the JSON file for the specified model.
Also, then the Schema checking (of the JSON file) could also be done simultaneously as the contributor fills out the Form.

**Comment by JaeyeongYang** [comment]
Close the issue since it uses YAML files instead of JSON files now.
