### ISSUE TITLE
extract_ic wrong `rep` function

### ISSUE THREAD

**Issue by Folquet** [CCS-Lab/hBayesDM#94]
`loo::extract_log_lik` stacks all Markov chains on top of each other, so the `chain_id` should be 1, 1, 1, 1, ..., 2, 2, 2, 2, ..., N, N, N, N. Yet the chain id is defined using `rep`, which by default uses the `times` argument. This leads to the result `rep(1:n_chains, nrow(lik)/n_chains)` = 1, 2, ..., N, 1, 2, ..., N

The rep call should therefore be changed to `rep(1:n_chains, each = nrow(lik)/n_chains)`

You might also consider updating the function code since `loo::extract_log_lik` implements the `merge_chains` argument which allows to separate chains automatically.

I am not an expert of the `loo` package, but I am afraid that this could be a serious source of miscalculation for model comparison...

**Comment by JaeyeongYang** [comment]
This issue is fixed on PR #100. Thanks for your report. :)
